//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceChecker4_8.Meb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UygulamaBilgileri", Namespace="http://schemas.datacontract.org/2004/07/CommonLibrary.Models")]
    [System.SerializableAttribute()]
    public partial class UygulamaBilgileri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciSifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UygulamaNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciSifre {
            get {
                return this.KullaniciSifreField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciSifreField, value) != true)) {
                    this.KullaniciSifreField = value;
                    this.RaisePropertyChanged("KullaniciSifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UygulamaNo {
            get {
                return this.UygulamaNoField;
            }
            set {
                if ((this.UygulamaNoField.Equals(value) != true)) {
                    this.UygulamaNoField = value;
                    this.RaisePropertyChanged("UygulamaNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ogrenci", Namespace="http://schemas.datacontract.org/2004/07/PASOServiceLib.Models")]
    [System.SerializableAttribute()]
    public partial class Ogrenci : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SinifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurKoduField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sinif {
            get {
                return this.SinifField;
            }
            set {
                if ((object.ReferenceEquals(this.SinifField, value) != true)) {
                    this.SinifField = value;
                    this.RaisePropertyChanged("Sinif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TurAdi {
            get {
                return this.TurAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.TurAdiField, value) != true)) {
                    this.TurAdiField = value;
                    this.RaisePropertyChanged("TurAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurKodu {
            get {
                return this.TurKoduField;
            }
            set {
                if ((this.TurKoduField.Equals(value) != true)) {
                    this.TurKoduField = value;
                    this.RaisePropertyChanged("TurKodu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ogretmen", Namespace="http://schemas.datacontract.org/2004/07/PASOServiceLib.Models")]
    [System.SerializableAttribute()]
    public partial class Ogretmen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KurumTuruField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Durum {
            get {
                return this.DurumField;
            }
            set {
                if ((object.ReferenceEquals(this.DurumField, value) != true)) {
                    this.DurumField = value;
                    this.RaisePropertyChanged("Durum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Il {
            get {
                return this.IlField;
            }
            set {
                if ((this.IlField.Equals(value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KurumTuru {
            get {
                return this.KurumTuruField;
            }
            set {
                if ((object.ReferenceEquals(this.KurumTuruField, value) != true)) {
                    this.KurumTuruField = value;
                    this.RaisePropertyChanged("KurumTuru");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://mebservis.meb.gov.tr/PASO/v2", ConfigurationName="Meb.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://mebservis.meb.gov.tr/PASO/v2/IService/OgrenciSorgula", ReplyAction="https://mebservis.meb.gov.tr/PASO/v2/IService/OgrenciSorgulaResponse")]
        ServiceChecker4_8.Meb.OgrenciSorgulaResponse OgrenciSorgula(ServiceChecker4_8.Meb.OgrenciSorgulaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://mebservis.meb.gov.tr/PASO/v2/IService/OgrenciSorgula", ReplyAction="https://mebservis.meb.gov.tr/PASO/v2/IService/OgrenciSorgulaResponse")]
        System.Threading.Tasks.Task<ServiceChecker4_8.Meb.OgrenciSorgulaResponse> OgrenciSorgulaAsync(ServiceChecker4_8.Meb.OgrenciSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://mebservis.meb.gov.tr/PASO/v2/IService/OgretmenSorgula", ReplyAction="https://mebservis.meb.gov.tr/PASO/v2/IService/OgretmenSorgulaResponse")]
        ServiceChecker4_8.Meb.OgretmenSorgulaResponse OgretmenSorgula(ServiceChecker4_8.Meb.OgretmenSorgulaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://mebservis.meb.gov.tr/PASO/v2/IService/OgretmenSorgula", ReplyAction="https://mebservis.meb.gov.tr/PASO/v2/IService/OgretmenSorgulaResponse")]
        System.Threading.Tasks.Task<ServiceChecker4_8.Meb.OgretmenSorgulaResponse> OgretmenSorgulaAsync(ServiceChecker4_8.Meb.OgretmenSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://mebservis.meb.gov.tr/PASO/v2/IService/YeniMezunSorgula", ReplyAction="https://mebservis.meb.gov.tr/PASO/v2/IService/YeniMezunSorgulaResponse")]
        ServiceChecker4_8.Meb.YeniMezunSorgulaResponse YeniMezunSorgula(ServiceChecker4_8.Meb.YeniMezunSorgulaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://mebservis.meb.gov.tr/PASO/v2/IService/YeniMezunSorgula", ReplyAction="https://mebservis.meb.gov.tr/PASO/v2/IService/YeniMezunSorgulaResponse")]
        System.Threading.Tasks.Task<ServiceChecker4_8.Meb.YeniMezunSorgulaResponse> YeniMezunSorgulaAsync(ServiceChecker4_8.Meb.YeniMezunSorgulaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OgrenciSorgulaRequestObject", WrapperNamespace="https://mebservis.meb.gov.tr/PASO/v2", IsWrapped=true)]
    public partial class OgrenciSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/PASO/v2", Order=0)]
        public long TCKimlikNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/PASO/v2", Order=1)]
        public ServiceChecker4_8.Meb.UygulamaBilgileri UygulamaBilgileri;
        
        public OgrenciSorgulaRequest() {
        }
        
        public OgrenciSorgulaRequest(long TCKimlikNo, ServiceChecker4_8.Meb.UygulamaBilgileri UygulamaBilgileri) {
            this.TCKimlikNo = TCKimlikNo;
            this.UygulamaBilgileri = UygulamaBilgileri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OgrenciSorgulaResponseObject", WrapperNamespace="https://mebservis.meb.gov.tr/PASO/v2", IsWrapped=true)]
    public partial class OgrenciSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/COMMON/v1", Order=0)]
        public string Aciklama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/COMMON/v1", Order=1)]
        public bool Basarili;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/COMMON/v1", Order=2)]
        public int SonucKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/PASO/v2", Order=3)]
        public ServiceChecker4_8.Meb.Ogrenci Ogrenci;
        
        public OgrenciSorgulaResponse() {
        }
        
        public OgrenciSorgulaResponse(string Aciklama, bool Basarili, int SonucKodu, ServiceChecker4_8.Meb.Ogrenci Ogrenci) {
            this.Aciklama = Aciklama;
            this.Basarili = Basarili;
            this.SonucKodu = SonucKodu;
            this.Ogrenci = Ogrenci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OgretmenSorgulaRequestObject", WrapperNamespace="https://mebservis.meb.gov.tr/PASO/v2", IsWrapped=true)]
    public partial class OgretmenSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/PASO/v2", Order=0)]
        public long TCKimlikNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/PASO/v2", Order=1)]
        public ServiceChecker4_8.Meb.UygulamaBilgileri UygulamaBilgileri;
        
        public OgretmenSorgulaRequest() {
        }
        
        public OgretmenSorgulaRequest(long TCKimlikNo, ServiceChecker4_8.Meb.UygulamaBilgileri UygulamaBilgileri) {
            this.TCKimlikNo = TCKimlikNo;
            this.UygulamaBilgileri = UygulamaBilgileri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OgretmenSorgulaResponseObject", WrapperNamespace="https://mebservis.meb.gov.tr/PASO/v2", IsWrapped=true)]
    public partial class OgretmenSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/COMMON/v1", Order=0)]
        public string Aciklama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/COMMON/v1", Order=1)]
        public bool Basarili;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/COMMON/v1", Order=2)]
        public int SonucKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/PASO/v2", Order=3)]
        public ServiceChecker4_8.Meb.Ogretmen Ogretmen;
        
        public OgretmenSorgulaResponse() {
        }
        
        public OgretmenSorgulaResponse(string Aciklama, bool Basarili, int SonucKodu, ServiceChecker4_8.Meb.Ogretmen Ogretmen) {
            this.Aciklama = Aciklama;
            this.Basarili = Basarili;
            this.SonucKodu = SonucKodu;
            this.Ogretmen = Ogretmen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="YeniMezunSorgulaRequestObject", WrapperNamespace="https://mebservis.meb.gov.tr/PASO/v2", IsWrapped=true)]
    public partial class YeniMezunSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/PASO/v2", Order=0)]
        public long TCKimlikNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/PASO/v2", Order=1)]
        public ServiceChecker4_8.Meb.UygulamaBilgileri UygulamaBilgileri;
        
        public YeniMezunSorgulaRequest() {
        }
        
        public YeniMezunSorgulaRequest(long TCKimlikNo, ServiceChecker4_8.Meb.UygulamaBilgileri UygulamaBilgileri) {
            this.TCKimlikNo = TCKimlikNo;
            this.UygulamaBilgileri = UygulamaBilgileri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="YeniMezunSorgulaResponseObject", WrapperNamespace="https://mebservis.meb.gov.tr/PASO/v2", IsWrapped=true)]
    public partial class YeniMezunSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/COMMON/v1", Order=0)]
        public string Aciklama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/COMMON/v1", Order=1)]
        public bool Basarili;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://mebservis.meb.gov.tr/COMMON/v1", Order=2)]
        public int SonucKodu;
        
        public YeniMezunSorgulaResponse() {
        }
        
        public YeniMezunSorgulaResponse(string Aciklama, bool Basarili, int SonucKodu) {
            this.Aciklama = Aciklama;
            this.Basarili = Basarili;
            this.SonucKodu = SonucKodu;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ServiceChecker4_8.Meb.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ServiceChecker4_8.Meb.IService>, ServiceChecker4_8.Meb.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceChecker4_8.Meb.OgrenciSorgulaResponse ServiceChecker4_8.Meb.IService.OgrenciSorgula(ServiceChecker4_8.Meb.OgrenciSorgulaRequest request) {
            return base.Channel.OgrenciSorgula(request);
        }
        
        public string OgrenciSorgula(long TCKimlikNo, ServiceChecker4_8.Meb.UygulamaBilgileri UygulamaBilgileri, out bool Basarili, out int SonucKodu, out ServiceChecker4_8.Meb.Ogrenci Ogrenci) {
            ServiceChecker4_8.Meb.OgrenciSorgulaRequest inValue = new ServiceChecker4_8.Meb.OgrenciSorgulaRequest();
            inValue.TCKimlikNo = TCKimlikNo;
            inValue.UygulamaBilgileri = UygulamaBilgileri;
            ServiceChecker4_8.Meb.OgrenciSorgulaResponse retVal = ((ServiceChecker4_8.Meb.IService)(this)).OgrenciSorgula(inValue);
            Basarili = retVal.Basarili;
            SonucKodu = retVal.SonucKodu;
            Ogrenci = retVal.Ogrenci;
            return retVal.Aciklama;
        }
        
        public System.Threading.Tasks.Task<ServiceChecker4_8.Meb.OgrenciSorgulaResponse> OgrenciSorgulaAsync(ServiceChecker4_8.Meb.OgrenciSorgulaRequest request) {
            return base.Channel.OgrenciSorgulaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceChecker4_8.Meb.OgretmenSorgulaResponse ServiceChecker4_8.Meb.IService.OgretmenSorgula(ServiceChecker4_8.Meb.OgretmenSorgulaRequest request) {
            return base.Channel.OgretmenSorgula(request);
        }
        
        public string OgretmenSorgula(long TCKimlikNo, ServiceChecker4_8.Meb.UygulamaBilgileri UygulamaBilgileri, out bool Basarili, out int SonucKodu, out ServiceChecker4_8.Meb.Ogretmen Ogretmen) {
            ServiceChecker4_8.Meb.OgretmenSorgulaRequest inValue = new ServiceChecker4_8.Meb.OgretmenSorgulaRequest();
            inValue.TCKimlikNo = TCKimlikNo;
            inValue.UygulamaBilgileri = UygulamaBilgileri;
            ServiceChecker4_8.Meb.OgretmenSorgulaResponse retVal = ((ServiceChecker4_8.Meb.IService)(this)).OgretmenSorgula(inValue);
            Basarili = retVal.Basarili;
            SonucKodu = retVal.SonucKodu;
            Ogretmen = retVal.Ogretmen;
            return retVal.Aciklama;
        }
        
        public System.Threading.Tasks.Task<ServiceChecker4_8.Meb.OgretmenSorgulaResponse> OgretmenSorgulaAsync(ServiceChecker4_8.Meb.OgretmenSorgulaRequest request) {
            return base.Channel.OgretmenSorgulaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceChecker4_8.Meb.YeniMezunSorgulaResponse ServiceChecker4_8.Meb.IService.YeniMezunSorgula(ServiceChecker4_8.Meb.YeniMezunSorgulaRequest request) {
            return base.Channel.YeniMezunSorgula(request);
        }
        
        public string YeniMezunSorgula(long TCKimlikNo, ServiceChecker4_8.Meb.UygulamaBilgileri UygulamaBilgileri, out bool Basarili, out int SonucKodu) {
            ServiceChecker4_8.Meb.YeniMezunSorgulaRequest inValue = new ServiceChecker4_8.Meb.YeniMezunSorgulaRequest();
            inValue.TCKimlikNo = TCKimlikNo;
            inValue.UygulamaBilgileri = UygulamaBilgileri;
            ServiceChecker4_8.Meb.YeniMezunSorgulaResponse retVal = ((ServiceChecker4_8.Meb.IService)(this)).YeniMezunSorgula(inValue);
            Basarili = retVal.Basarili;
            SonucKodu = retVal.SonucKodu;
            return retVal.Aciklama;
        }
        
        public System.Threading.Tasks.Task<ServiceChecker4_8.Meb.YeniMezunSorgulaResponse> YeniMezunSorgulaAsync(ServiceChecker4_8.Meb.YeniMezunSorgulaRequest request) {
            return base.Channel.YeniMezunSorgulaAsync(request);
        }
    }
}
