//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceChecker4_8.TCKimlikAdresSorgula {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileAdresSorguKriteri", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class KimlikNoileAdresSorguKriteri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DogumAyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DogumGunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DogumYilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> KimlikNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumAy {
            get {
                return this.DogumAyField;
            }
            set {
                if ((this.DogumAyField.Equals(value) != true)) {
                    this.DogumAyField = value;
                    this.RaisePropertyChanged("DogumAy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumGun {
            get {
                return this.DogumGunField;
            }
            set {
                if ((this.DogumGunField.Equals(value) != true)) {
                    this.DogumGunField = value;
                    this.RaisePropertyChanged("DogumGun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumYil {
            get {
                return this.DogumYilField;
            }
            set {
                if ((this.DogumYilField.Equals(value) != true)) {
                    this.DogumYilField = value;
                    this.RaisePropertyChanged("DogumYil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo {
            get {
                return this.KimlikNoField;
            }
            set {
                if ((this.KimlikNoField.Equals(value) != true)) {
                    this.KimlikNoField = value;
                    this.RaisePropertyChanged("KimlikNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileKisiAdresBilgileriSonucu", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class KimlikNoileKisiAdresBilgileriSonucu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKisiAdresBilgileri> SorguSonucuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKisiAdresBilgileri> SorguSonucu {
            get {
                return this.SorguSonucuField;
            }
            set {
                if ((object.ReferenceEquals(this.SorguSonucuField, value) != true)) {
                    this.SorguSonucuField = value;
                    this.RaisePropertyChanged("SorguSonucu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametre", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class Parametre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kod {
            get {
                return this.KodField;
            }
            set {
                if ((this.KodField.Equals(value) != true)) {
                    this.KodField = value;
                    this.RaisePropertyChanged("Kod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileKisiAdresBilgileri", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class KimlikNoileKisiAdresBilgileri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKisiAdresBilgisi> DigerAdresBilgileriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> KimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKisiAdresBilgisi YerlesimYeriAdresiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKisiAdresBilgisi> DigerAdresBilgileri {
            get {
                return this.DigerAdresBilgileriField;
            }
            set {
                if ((object.ReferenceEquals(this.DigerAdresBilgileriField, value) != true)) {
                    this.DigerAdresBilgileriField = value;
                    this.RaisePropertyChanged("DigerAdresBilgileri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo {
            get {
                return this.KimlikNoField;
            }
            set {
                if ((this.KimlikNoField.Equals(value) != true)) {
                    this.KimlikNoField = value;
                    this.RaisePropertyChanged("KimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKisiAdresBilgisi YerlesimYeriAdresi {
            get {
                return this.YerlesimYeriAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.YerlesimYeriAdresiField, value) != true)) {
                    this.YerlesimYeriAdresiField = value;
                    this.RaisePropertyChanged("YerlesimYeriAdresi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileKisiAdresBilgisi", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class KimlikNoileKisiAdresBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcikAdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AdresNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre AdresTipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileBeldeAdresi BeldeAdresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.TarihBilgisi BeyanTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BeyandaBulunanKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileIlIlceMerkezi IlIlceMerkezAdresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKoyAdresi KoyAdresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre TasinmaNedenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TasinmaNedenAciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.TarihBilgisi TasinmaTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.TarihBilgisi TescilTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileYurtDisiAdresi YurtDisiAdresiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcikAdres {
            get {
                return this.AcikAdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AcikAdresField, value) != true)) {
                    this.AcikAdresField = value;
                    this.RaisePropertyChanged("AcikAdres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AdresNo {
            get {
                return this.AdresNoField;
            }
            set {
                if ((this.AdresNoField.Equals(value) != true)) {
                    this.AdresNoField = value;
                    this.RaisePropertyChanged("AdresNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre AdresTip {
            get {
                return this.AdresTipField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresTipField, value) != true)) {
                    this.AdresTipField = value;
                    this.RaisePropertyChanged("AdresTip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileBeldeAdresi BeldeAdresi {
            get {
                return this.BeldeAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.BeldeAdresiField, value) != true)) {
                    this.BeldeAdresiField = value;
                    this.RaisePropertyChanged("BeldeAdresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.TarihBilgisi BeyanTarihi {
            get {
                return this.BeyanTarihiField;
            }
            set {
                if ((object.ReferenceEquals(this.BeyanTarihiField, value) != true)) {
                    this.BeyanTarihiField = value;
                    this.RaisePropertyChanged("BeyanTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BeyandaBulunanKimlikNo {
            get {
                return this.BeyandaBulunanKimlikNoField;
            }
            set {
                if ((this.BeyandaBulunanKimlikNoField.Equals(value) != true)) {
                    this.BeyandaBulunanKimlikNoField = value;
                    this.RaisePropertyChanged("BeyandaBulunanKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileIlIlceMerkezi IlIlceMerkezAdresi {
            get {
                return this.IlIlceMerkezAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.IlIlceMerkezAdresiField, value) != true)) {
                    this.IlIlceMerkezAdresiField = value;
                    this.RaisePropertyChanged("IlIlceMerkezAdresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKoyAdresi KoyAdresi {
            get {
                return this.KoyAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.KoyAdresiField, value) != true)) {
                    this.KoyAdresiField = value;
                    this.RaisePropertyChanged("KoyAdresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre TasinmaNeden {
            get {
                return this.TasinmaNedenField;
            }
            set {
                if ((object.ReferenceEquals(this.TasinmaNedenField, value) != true)) {
                    this.TasinmaNedenField = value;
                    this.RaisePropertyChanged("TasinmaNeden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TasinmaNedenAciklama {
            get {
                return this.TasinmaNedenAciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.TasinmaNedenAciklamaField, value) != true)) {
                    this.TasinmaNedenAciklamaField = value;
                    this.RaisePropertyChanged("TasinmaNedenAciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.TarihBilgisi TasinmaTarihi {
            get {
                return this.TasinmaTarihiField;
            }
            set {
                if ((object.ReferenceEquals(this.TasinmaTarihiField, value) != true)) {
                    this.TasinmaTarihiField = value;
                    this.RaisePropertyChanged("TasinmaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.TarihBilgisi TescilTarihi {
            get {
                return this.TescilTarihiField;
            }
            set {
                if ((object.ReferenceEquals(this.TescilTarihiField, value) != true)) {
                    this.TescilTarihiField = value;
                    this.RaisePropertyChanged("TescilTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileYurtDisiAdresi YurtDisiAdresi {
            get {
                return this.YurtDisiAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.YurtDisiAdresiField, value) != true)) {
                    this.YurtDisiAdresiField = value;
                    this.RaisePropertyChanged("YurtDisiAdresi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileBeldeAdresi", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class KimlikNoileBeldeAdresi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaAdaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaBlokAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BinaKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BinaNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaNumaratajTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaPaftaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaParselField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaSiteAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaYapiTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CsbmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CsbmKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlceKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KatNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KoyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> KoyKayitNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> KoyKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MahalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MahalleKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TapuBagimsizBolumNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre YapiKullanimAmacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YolAltiKatSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YolUstuKatSayisiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumDurum {
            get {
                return this.BagimsizBolumDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.BagimsizBolumDurumField, value) != true)) {
                    this.BagimsizBolumDurumField = value;
                    this.RaisePropertyChanged("BagimsizBolumDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumTipi {
            get {
                return this.BagimsizBolumTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.BagimsizBolumTipiField, value) != true)) {
                    this.BagimsizBolumTipiField = value;
                    this.RaisePropertyChanged("BagimsizBolumTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaAda {
            get {
                return this.BinaAdaField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaAdaField, value) != true)) {
                    this.BinaAdaField = value;
                    this.RaisePropertyChanged("BinaAda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaBlokAdi {
            get {
                return this.BinaBlokAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaBlokAdiField, value) != true)) {
                    this.BinaBlokAdiField = value;
                    this.RaisePropertyChanged("BinaBlokAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaDurum {
            get {
                return this.BinaDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaDurumField, value) != true)) {
                    this.BinaDurumField = value;
                    this.RaisePropertyChanged("BinaDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BinaKodu {
            get {
                return this.BinaKoduField;
            }
            set {
                if ((this.BinaKoduField.Equals(value) != true)) {
                    this.BinaKoduField = value;
                    this.RaisePropertyChanged("BinaKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BinaNo {
            get {
                return this.BinaNoField;
            }
            set {
                if ((this.BinaNoField.Equals(value) != true)) {
                    this.BinaNoField = value;
                    this.RaisePropertyChanged("BinaNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaNumaratajTipi {
            get {
                return this.BinaNumaratajTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaNumaratajTipiField, value) != true)) {
                    this.BinaNumaratajTipiField = value;
                    this.RaisePropertyChanged("BinaNumaratajTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaPafta {
            get {
                return this.BinaPaftaField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaPaftaField, value) != true)) {
                    this.BinaPaftaField = value;
                    this.RaisePropertyChanged("BinaPafta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaParsel {
            get {
                return this.BinaParselField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaParselField, value) != true)) {
                    this.BinaParselField = value;
                    this.RaisePropertyChanged("BinaParsel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaSiteAdi {
            get {
                return this.BinaSiteAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaSiteAdiField, value) != true)) {
                    this.BinaSiteAdiField = value;
                    this.RaisePropertyChanged("BinaSiteAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaYapiTipi {
            get {
                return this.BinaYapiTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaYapiTipiField, value) != true)) {
                    this.BinaYapiTipiField = value;
                    this.RaisePropertyChanged("BinaYapiTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Csbm {
            get {
                return this.CsbmField;
            }
            set {
                if ((object.ReferenceEquals(this.CsbmField, value) != true)) {
                    this.CsbmField = value;
                    this.RaisePropertyChanged("Csbm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CsbmKodu {
            get {
                return this.CsbmKoduField;
            }
            set {
                if ((this.CsbmKoduField.Equals(value) != true)) {
                    this.CsbmKoduField = value;
                    this.RaisePropertyChanged("CsbmKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisKapiNo {
            get {
                return this.DisKapiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DisKapiNoField, value) != true)) {
                    this.DisKapiNoField = value;
                    this.RaisePropertyChanged("DisKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IcKapiNo {
            get {
                return this.IcKapiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IcKapiNoField, value) != true)) {
                    this.IcKapiNoField = value;
                    this.RaisePropertyChanged("IcKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il {
            get {
                return this.IlField;
            }
            set {
                if ((object.ReferenceEquals(this.IlField, value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlKodu {
            get {
                return this.IlKoduField;
            }
            set {
                if ((this.IlKoduField.Equals(value) != true)) {
                    this.IlKoduField = value;
                    this.RaisePropertyChanged("IlKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlceKodu {
            get {
                return this.IlceKoduField;
            }
            set {
                if ((this.IlceKoduField.Equals(value) != true)) {
                    this.IlceKoduField = value;
                    this.RaisePropertyChanged("IlceKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KatNo {
            get {
                return this.KatNoField;
            }
            set {
                if ((object.ReferenceEquals(this.KatNoField, value) != true)) {
                    this.KatNoField = value;
                    this.RaisePropertyChanged("KatNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Koy {
            get {
                return this.KoyField;
            }
            set {
                if ((object.ReferenceEquals(this.KoyField, value) != true)) {
                    this.KoyField = value;
                    this.RaisePropertyChanged("Koy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKayitNo {
            get {
                return this.KoyKayitNoField;
            }
            set {
                if ((this.KoyKayitNoField.Equals(value) != true)) {
                    this.KoyKayitNoField = value;
                    this.RaisePropertyChanged("KoyKayitNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKodu {
            get {
                return this.KoyKoduField;
            }
            set {
                if ((this.KoyKoduField.Equals(value) != true)) {
                    this.KoyKoduField = value;
                    this.RaisePropertyChanged("KoyKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahalle {
            get {
                return this.MahalleField;
            }
            set {
                if ((object.ReferenceEquals(this.MahalleField, value) != true)) {
                    this.MahalleField = value;
                    this.RaisePropertyChanged("Mahalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MahalleKodu {
            get {
                return this.MahalleKoduField;
            }
            set {
                if ((this.MahalleKoduField.Equals(value) != true)) {
                    this.MahalleKoduField = value;
                    this.RaisePropertyChanged("MahalleKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TapuBagimsizBolumNo {
            get {
                return this.TapuBagimsizBolumNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TapuBagimsizBolumNoField, value) != true)) {
                    this.TapuBagimsizBolumNoField = value;
                    this.RaisePropertyChanged("TapuBagimsizBolumNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre YapiKullanimAmac {
            get {
                return this.YapiKullanimAmacField;
            }
            set {
                if ((object.ReferenceEquals(this.YapiKullanimAmacField, value) != true)) {
                    this.YapiKullanimAmacField = value;
                    this.RaisePropertyChanged("YapiKullanimAmac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolAltiKatSayisi {
            get {
                return this.YolAltiKatSayisiField;
            }
            set {
                if ((this.YolAltiKatSayisiField.Equals(value) != true)) {
                    this.YolAltiKatSayisiField = value;
                    this.RaisePropertyChanged("YolAltiKatSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolUstuKatSayisi {
            get {
                return this.YolUstuKatSayisiField;
            }
            set {
                if ((this.YolUstuKatSayisiField.Equals(value) != true)) {
                    this.YolUstuKatSayisiField = value;
                    this.RaisePropertyChanged("YolUstuKatSayisi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TarihBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class TarihBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ay {
            get {
                return this.AyField;
            }
            set {
                if ((this.AyField.Equals(value) != true)) {
                    this.AyField = value;
                    this.RaisePropertyChanged("Ay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gun {
            get {
                return this.GunField;
            }
            set {
                if ((this.GunField.Equals(value) != true)) {
                    this.GunField = value;
                    this.RaisePropertyChanged("Gun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Yil {
            get {
                return this.YilField;
            }
            set {
                if ((this.YilField.Equals(value) != true)) {
                    this.YilField = value;
                    this.RaisePropertyChanged("Yil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileIlIlceMerkezi", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class KimlikNoileIlIlceMerkezi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaAdaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaBlokAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BinaKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BinaNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaNumaratajTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaPaftaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaParselField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaSiteAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaYapiTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CsbmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CsbmKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlceKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KatNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MahalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MahalleKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TapuBagimsizBolumNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre YapiKullanimAmacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YolAltiKatSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YolUstuKatSayisiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumDurum {
            get {
                return this.BagimsizBolumDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.BagimsizBolumDurumField, value) != true)) {
                    this.BagimsizBolumDurumField = value;
                    this.RaisePropertyChanged("BagimsizBolumDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumTipi {
            get {
                return this.BagimsizBolumTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.BagimsizBolumTipiField, value) != true)) {
                    this.BagimsizBolumTipiField = value;
                    this.RaisePropertyChanged("BagimsizBolumTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaAda {
            get {
                return this.BinaAdaField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaAdaField, value) != true)) {
                    this.BinaAdaField = value;
                    this.RaisePropertyChanged("BinaAda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaBlokAdi {
            get {
                return this.BinaBlokAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaBlokAdiField, value) != true)) {
                    this.BinaBlokAdiField = value;
                    this.RaisePropertyChanged("BinaBlokAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaDurum {
            get {
                return this.BinaDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaDurumField, value) != true)) {
                    this.BinaDurumField = value;
                    this.RaisePropertyChanged("BinaDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BinaKodu {
            get {
                return this.BinaKoduField;
            }
            set {
                if ((this.BinaKoduField.Equals(value) != true)) {
                    this.BinaKoduField = value;
                    this.RaisePropertyChanged("BinaKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BinaNo {
            get {
                return this.BinaNoField;
            }
            set {
                if ((this.BinaNoField.Equals(value) != true)) {
                    this.BinaNoField = value;
                    this.RaisePropertyChanged("BinaNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaNumaratajTipi {
            get {
                return this.BinaNumaratajTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaNumaratajTipiField, value) != true)) {
                    this.BinaNumaratajTipiField = value;
                    this.RaisePropertyChanged("BinaNumaratajTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaPafta {
            get {
                return this.BinaPaftaField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaPaftaField, value) != true)) {
                    this.BinaPaftaField = value;
                    this.RaisePropertyChanged("BinaPafta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaParsel {
            get {
                return this.BinaParselField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaParselField, value) != true)) {
                    this.BinaParselField = value;
                    this.RaisePropertyChanged("BinaParsel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaSiteAdi {
            get {
                return this.BinaSiteAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaSiteAdiField, value) != true)) {
                    this.BinaSiteAdiField = value;
                    this.RaisePropertyChanged("BinaSiteAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaYapiTipi {
            get {
                return this.BinaYapiTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaYapiTipiField, value) != true)) {
                    this.BinaYapiTipiField = value;
                    this.RaisePropertyChanged("BinaYapiTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Csbm {
            get {
                return this.CsbmField;
            }
            set {
                if ((object.ReferenceEquals(this.CsbmField, value) != true)) {
                    this.CsbmField = value;
                    this.RaisePropertyChanged("Csbm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CsbmKodu {
            get {
                return this.CsbmKoduField;
            }
            set {
                if ((this.CsbmKoduField.Equals(value) != true)) {
                    this.CsbmKoduField = value;
                    this.RaisePropertyChanged("CsbmKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisKapiNo {
            get {
                return this.DisKapiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DisKapiNoField, value) != true)) {
                    this.DisKapiNoField = value;
                    this.RaisePropertyChanged("DisKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IcKapiNo {
            get {
                return this.IcKapiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IcKapiNoField, value) != true)) {
                    this.IcKapiNoField = value;
                    this.RaisePropertyChanged("IcKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il {
            get {
                return this.IlField;
            }
            set {
                if ((object.ReferenceEquals(this.IlField, value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlKodu {
            get {
                return this.IlKoduField;
            }
            set {
                if ((this.IlKoduField.Equals(value) != true)) {
                    this.IlKoduField = value;
                    this.RaisePropertyChanged("IlKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlceKodu {
            get {
                return this.IlceKoduField;
            }
            set {
                if ((this.IlceKoduField.Equals(value) != true)) {
                    this.IlceKoduField = value;
                    this.RaisePropertyChanged("IlceKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KatNo {
            get {
                return this.KatNoField;
            }
            set {
                if ((object.ReferenceEquals(this.KatNoField, value) != true)) {
                    this.KatNoField = value;
                    this.RaisePropertyChanged("KatNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahalle {
            get {
                return this.MahalleField;
            }
            set {
                if ((object.ReferenceEquals(this.MahalleField, value) != true)) {
                    this.MahalleField = value;
                    this.RaisePropertyChanged("Mahalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MahalleKodu {
            get {
                return this.MahalleKoduField;
            }
            set {
                if ((this.MahalleKoduField.Equals(value) != true)) {
                    this.MahalleKoduField = value;
                    this.RaisePropertyChanged("MahalleKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TapuBagimsizBolumNo {
            get {
                return this.TapuBagimsizBolumNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TapuBagimsizBolumNoField, value) != true)) {
                    this.TapuBagimsizBolumNoField = value;
                    this.RaisePropertyChanged("TapuBagimsizBolumNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre YapiKullanimAmac {
            get {
                return this.YapiKullanimAmacField;
            }
            set {
                if ((object.ReferenceEquals(this.YapiKullanimAmacField, value) != true)) {
                    this.YapiKullanimAmacField = value;
                    this.RaisePropertyChanged("YapiKullanimAmac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolAltiKatSayisi {
            get {
                return this.YolAltiKatSayisiField;
            }
            set {
                if ((this.YolAltiKatSayisiField.Equals(value) != true)) {
                    this.YolAltiKatSayisiField = value;
                    this.RaisePropertyChanged("YolAltiKatSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolUstuKatSayisi {
            get {
                return this.YolUstuKatSayisiField;
            }
            set {
                if ((this.YolUstuKatSayisiField.Equals(value) != true)) {
                    this.YolUstuKatSayisiField = value;
                    this.RaisePropertyChanged("YolUstuKatSayisi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileKoyAdresi", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class KimlikNoileKoyAdresi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaAdaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaBlokAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BinaKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BinaNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaNumaratajTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaPaftaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaParselField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinaSiteAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaYapiTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CsbmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CsbmKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlceKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KatNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KoyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> KoyKayitNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> KoyKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MahalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MahalleKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TapuBagimsizBolumNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre YapiKullanimAmacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YolAltiKatSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YolUstuKatSayisiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumDurum {
            get {
                return this.BagimsizBolumDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.BagimsizBolumDurumField, value) != true)) {
                    this.BagimsizBolumDurumField = value;
                    this.RaisePropertyChanged("BagimsizBolumDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BagimsizBolumTipi {
            get {
                return this.BagimsizBolumTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.BagimsizBolumTipiField, value) != true)) {
                    this.BagimsizBolumTipiField = value;
                    this.RaisePropertyChanged("BagimsizBolumTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaAda {
            get {
                return this.BinaAdaField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaAdaField, value) != true)) {
                    this.BinaAdaField = value;
                    this.RaisePropertyChanged("BinaAda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaBlokAdi {
            get {
                return this.BinaBlokAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaBlokAdiField, value) != true)) {
                    this.BinaBlokAdiField = value;
                    this.RaisePropertyChanged("BinaBlokAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaDurum {
            get {
                return this.BinaDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaDurumField, value) != true)) {
                    this.BinaDurumField = value;
                    this.RaisePropertyChanged("BinaDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BinaKodu {
            get {
                return this.BinaKoduField;
            }
            set {
                if ((this.BinaKoduField.Equals(value) != true)) {
                    this.BinaKoduField = value;
                    this.RaisePropertyChanged("BinaKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BinaNo {
            get {
                return this.BinaNoField;
            }
            set {
                if ((this.BinaNoField.Equals(value) != true)) {
                    this.BinaNoField = value;
                    this.RaisePropertyChanged("BinaNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaNumaratajTipi {
            get {
                return this.BinaNumaratajTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaNumaratajTipiField, value) != true)) {
                    this.BinaNumaratajTipiField = value;
                    this.RaisePropertyChanged("BinaNumaratajTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaPafta {
            get {
                return this.BinaPaftaField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaPaftaField, value) != true)) {
                    this.BinaPaftaField = value;
                    this.RaisePropertyChanged("BinaPafta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaParsel {
            get {
                return this.BinaParselField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaParselField, value) != true)) {
                    this.BinaParselField = value;
                    this.RaisePropertyChanged("BinaParsel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaSiteAdi {
            get {
                return this.BinaSiteAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaSiteAdiField, value) != true)) {
                    this.BinaSiteAdiField = value;
                    this.RaisePropertyChanged("BinaSiteAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre BinaYapiTipi {
            get {
                return this.BinaYapiTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaYapiTipiField, value) != true)) {
                    this.BinaYapiTipiField = value;
                    this.RaisePropertyChanged("BinaYapiTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Csbm {
            get {
                return this.CsbmField;
            }
            set {
                if ((object.ReferenceEquals(this.CsbmField, value) != true)) {
                    this.CsbmField = value;
                    this.RaisePropertyChanged("Csbm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CsbmKodu {
            get {
                return this.CsbmKoduField;
            }
            set {
                if ((this.CsbmKoduField.Equals(value) != true)) {
                    this.CsbmKoduField = value;
                    this.RaisePropertyChanged("CsbmKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisKapiNo {
            get {
                return this.DisKapiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DisKapiNoField, value) != true)) {
                    this.DisKapiNoField = value;
                    this.RaisePropertyChanged("DisKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IcKapiNo {
            get {
                return this.IcKapiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IcKapiNoField, value) != true)) {
                    this.IcKapiNoField = value;
                    this.RaisePropertyChanged("IcKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il {
            get {
                return this.IlField;
            }
            set {
                if ((object.ReferenceEquals(this.IlField, value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlKodu {
            get {
                return this.IlKoduField;
            }
            set {
                if ((this.IlKoduField.Equals(value) != true)) {
                    this.IlKoduField = value;
                    this.RaisePropertyChanged("IlKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlceKodu {
            get {
                return this.IlceKoduField;
            }
            set {
                if ((this.IlceKoduField.Equals(value) != true)) {
                    this.IlceKoduField = value;
                    this.RaisePropertyChanged("IlceKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KatNo {
            get {
                return this.KatNoField;
            }
            set {
                if ((object.ReferenceEquals(this.KatNoField, value) != true)) {
                    this.KatNoField = value;
                    this.RaisePropertyChanged("KatNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Koy {
            get {
                return this.KoyField;
            }
            set {
                if ((object.ReferenceEquals(this.KoyField, value) != true)) {
                    this.KoyField = value;
                    this.RaisePropertyChanged("Koy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKayitNo {
            get {
                return this.KoyKayitNoField;
            }
            set {
                if ((this.KoyKayitNoField.Equals(value) != true)) {
                    this.KoyKayitNoField = value;
                    this.RaisePropertyChanged("KoyKayitNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKodu {
            get {
                return this.KoyKoduField;
            }
            set {
                if ((this.KoyKoduField.Equals(value) != true)) {
                    this.KoyKoduField = value;
                    this.RaisePropertyChanged("KoyKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahalle {
            get {
                return this.MahalleField;
            }
            set {
                if ((object.ReferenceEquals(this.MahalleField, value) != true)) {
                    this.MahalleField = value;
                    this.RaisePropertyChanged("Mahalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MahalleKodu {
            get {
                return this.MahalleKoduField;
            }
            set {
                if ((this.MahalleKoduField.Equals(value) != true)) {
                    this.MahalleKoduField = value;
                    this.RaisePropertyChanged("MahalleKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TapuBagimsizBolumNo {
            get {
                return this.TapuBagimsizBolumNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TapuBagimsizBolumNoField, value) != true)) {
                    this.TapuBagimsizBolumNoField = value;
                    this.RaisePropertyChanged("TapuBagimsizBolumNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre YapiKullanimAmac {
            get {
                return this.YapiKullanimAmacField;
            }
            set {
                if ((object.ReferenceEquals(this.YapiKullanimAmacField, value) != true)) {
                    this.YapiKullanimAmacField = value;
                    this.RaisePropertyChanged("YapiKullanimAmac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolAltiKatSayisi {
            get {
                return this.YolAltiKatSayisiField;
            }
            set {
                if ((this.YolAltiKatSayisiField.Equals(value) != true)) {
                    this.YolAltiKatSayisiField = value;
                    this.RaisePropertyChanged("YolAltiKatSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolUstuKatSayisi {
            get {
                return this.YolUstuKatSayisiField;
            }
            set {
                if ((this.YolUstuKatSayisiField.Equals(value) != true)) {
                    this.YolUstuKatSayisiField = value;
                    this.RaisePropertyChanged("YolUstuKatSayisi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileYurtDisiAdresi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KimlikNoileYurtDisiAdresi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DisTemsDuzeltmeBeyanTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DisTemsDuzeltmeKararTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre DisTemsDuzeltmeNedenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre DisTemsilcilikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YabanciAdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YabanciSehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.TCKimlikAdresSorgula.Parametre YabanciUlkeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DisTemsDuzeltmeBeyanTarih {
            get {
                return this.DisTemsDuzeltmeBeyanTarihField;
            }
            set {
                if ((this.DisTemsDuzeltmeBeyanTarihField.Equals(value) != true)) {
                    this.DisTemsDuzeltmeBeyanTarihField = value;
                    this.RaisePropertyChanged("DisTemsDuzeltmeBeyanTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DisTemsDuzeltmeKararTarih {
            get {
                return this.DisTemsDuzeltmeKararTarihField;
            }
            set {
                if ((this.DisTemsDuzeltmeKararTarihField.Equals(value) != true)) {
                    this.DisTemsDuzeltmeKararTarihField = value;
                    this.RaisePropertyChanged("DisTemsDuzeltmeKararTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre DisTemsDuzeltmeNeden {
            get {
                return this.DisTemsDuzeltmeNedenField;
            }
            set {
                if ((object.ReferenceEquals(this.DisTemsDuzeltmeNedenField, value) != true)) {
                    this.DisTemsDuzeltmeNedenField = value;
                    this.RaisePropertyChanged("DisTemsDuzeltmeNeden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre DisTemsilcilik {
            get {
                return this.DisTemsilcilikField;
            }
            set {
                if ((object.ReferenceEquals(this.DisTemsilcilikField, value) != true)) {
                    this.DisTemsilcilikField = value;
                    this.RaisePropertyChanged("DisTemsilcilik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YabanciAdres {
            get {
                return this.YabanciAdresField;
            }
            set {
                if ((object.ReferenceEquals(this.YabanciAdresField, value) != true)) {
                    this.YabanciAdresField = value;
                    this.RaisePropertyChanged("YabanciAdres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YabanciSehir {
            get {
                return this.YabanciSehirField;
            }
            set {
                if ((object.ReferenceEquals(this.YabanciSehirField, value) != true)) {
                    this.YabanciSehirField = value;
                    this.RaisePropertyChanged("YabanciSehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.TCKimlikAdresSorgula.Parametre YabanciUlke {
            get {
                return this.YabanciUlkeField;
            }
            set {
                if ((object.ReferenceEquals(this.YabanciUlkeField, value) != true)) {
                    this.YabanciUlkeField = value;
                    this.RaisePropertyChanged("YabanciUlke");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kps.nvi.gov.tr/2021/04/01", ConfigurationName="TCKimlikAdresSorgula.KimlikNoSorgulaAdresServis")]
    public interface KimlikNoSorgulaAdresServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kps.nvi.gov.tr/2021/04/01/KimlikNoSorgulaAdresServis/Sorgula", ReplyAction="http://kps.nvi.gov.tr/2021/04/01/KimlikNoSorgulaAdresServis/SorgulaResponse")]
        ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKisiAdresBilgileriSonucu Sorgula(System.Collections.Generic.List<ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileAdresSorguKriteri> kriterListesi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kps.nvi.gov.tr/2021/04/01/KimlikNoSorgulaAdresServis/Sorgula", ReplyAction="http://kps.nvi.gov.tr/2021/04/01/KimlikNoSorgulaAdresServis/SorgulaResponse")]
        System.Threading.Tasks.Task<ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKisiAdresBilgileriSonucu> SorgulaAsync(System.Collections.Generic.List<ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileAdresSorguKriteri> kriterListesi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KimlikNoSorgulaAdresServisChannel : ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoSorgulaAdresServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KimlikNoSorgulaAdresServisClient : System.ServiceModel.ClientBase<ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoSorgulaAdresServis>, ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoSorgulaAdresServis {
        
        public KimlikNoSorgulaAdresServisClient() {
        }
        
        public KimlikNoSorgulaAdresServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KimlikNoSorgulaAdresServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KimlikNoSorgulaAdresServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KimlikNoSorgulaAdresServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKisiAdresBilgileriSonucu Sorgula(System.Collections.Generic.List<ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileAdresSorguKriteri> kriterListesi) {
            return base.Channel.Sorgula(kriterListesi);
        }
        
        public System.Threading.Tasks.Task<ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileKisiAdresBilgileriSonucu> SorgulaAsync(System.Collections.Generic.List<ServiceChecker4_8.TCKimlikAdresSorgula.KimlikNoileAdresSorguKriteri> kriterListesi) {
            return base.Channel.SorgulaAsync(kriterListesi);
        }
    }
}
