//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceChecker4_8.NufusKayitOrnegi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NkoTCKimlikNoSorguKriteri", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class NkoTCKimlikNoSorguKriteri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DogumAyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DogumGunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DogumYilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EskiEsListeleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ServiceChecker4_8.NufusKayitOrnegi.NkoTur> NKOTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> VukuatliField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumAy {
            get {
                return this.DogumAyField;
            }
            set {
                if ((this.DogumAyField.Equals(value) != true)) {
                    this.DogumAyField = value;
                    this.RaisePropertyChanged("DogumAy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumGun {
            get {
                return this.DogumGunField;
            }
            set {
                if ((this.DogumGunField.Equals(value) != true)) {
                    this.DogumGunField = value;
                    this.RaisePropertyChanged("DogumGun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumYil {
            get {
                return this.DogumYilField;
            }
            set {
                if ((this.DogumYilField.Equals(value) != true)) {
                    this.DogumYilField = value;
                    this.RaisePropertyChanged("DogumYil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EskiEsListele {
            get {
                return this.EskiEsListeleField;
            }
            set {
                if ((this.EskiEsListeleField.Equals(value) != true)) {
                    this.EskiEsListeleField = value;
                    this.RaisePropertyChanged("EskiEsListele");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceChecker4_8.NufusKayitOrnegi.NkoTur> NKOTipi {
            get {
                return this.NKOTipiField;
            }
            set {
                if ((this.NKOTipiField.Equals(value) != true)) {
                    this.NKOTipiField = value;
                    this.RaisePropertyChanged("NKOTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo {
            get {
                return this.TCKimlikNoField;
            }
            set {
                if ((this.TCKimlikNoField.Equals(value) != true)) {
                    this.TCKimlikNoField = value;
                    this.RaisePropertyChanged("TCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Vukuatli {
            get {
                return this.VukuatliField;
            }
            set {
                if ((this.VukuatliField.Equals(value) != true)) {
                    this.VukuatliField = value;
                    this.RaisePropertyChanged("Vukuatli");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NkoTur", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public enum NkoTur : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KisiKayitOrnek = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AileKayitOrnek = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NufusAileKayitOrnek = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NufusAileKayitOrnekKardesDahil = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NkoSonucu", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class NkoSonucu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Nko[] SorguSonucuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Nko[] SorguSonucu {
            get {
                return this.SorguSonucuField;
            }
            set {
                if ((object.ReferenceEquals(this.SorguSonucuField, value) != true)) {
                    this.SorguSonucuField = value;
                    this.RaisePropertyChanged("SorguSonucu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametre", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class Parametre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kod {
            get {
                return this.KodField;
            }
            set {
                if ((this.KodField.Equals(value) != true)) {
                    this.KodField = value;
                    this.RaisePropertyChanged("Kod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nko", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class Nko : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.NkoKisi[] KisilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre NkoTuruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.NkoOlay[] OlaylarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.NkoKisi[] Kisiler {
            get {
                return this.KisilerField;
            }
            set {
                if ((object.ReferenceEquals(this.KisilerField, value) != true)) {
                    this.KisilerField = value;
                    this.RaisePropertyChanged("Kisiler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre NkoTuru {
            get {
                return this.NkoTuruField;
            }
            set {
                if ((object.ReferenceEquals(this.NkoTuruField, value) != true)) {
                    this.NkoTuruField = value;
                    this.RaisePropertyChanged("NkoTuru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.NkoOlay[] Olaylar {
            get {
                return this.OlaylarField;
            }
            set {
                if ((object.ReferenceEquals(this.OlaylarField, value) != true)) {
                    this.OlaylarField = value;
                    this.RaisePropertyChanged("Olaylar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NkoKisi", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class NkoKisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.KisiDurumBilgisi DurumBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.KisiKayitYeriBilgisi KayitYeriBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.OlayTarihBilgisi KisiOlayTarihBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.KisiTemelBilgisi TemelBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre YakinlikKodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.KisiDurumBilgisi DurumBilgisi {
            get {
                return this.DurumBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.DurumBilgisiField, value) != true)) {
                    this.DurumBilgisiField = value;
                    this.RaisePropertyChanged("DurumBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.KisiKayitYeriBilgisi KayitYeriBilgisi {
            get {
                return this.KayitYeriBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.KayitYeriBilgisiField, value) != true)) {
                    this.KayitYeriBilgisiField = value;
                    this.RaisePropertyChanged("KayitYeriBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.OlayTarihBilgisi KisiOlayTarihBilgisi {
            get {
                return this.KisiOlayTarihBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.KisiOlayTarihBilgisiField, value) != true)) {
                    this.KisiOlayTarihBilgisiField = value;
                    this.RaisePropertyChanged("KisiOlayTarihBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo {
            get {
                return this.TCKimlikNoField;
            }
            set {
                if ((this.TCKimlikNoField.Equals(value) != true)) {
                    this.TCKimlikNoField = value;
                    this.RaisePropertyChanged("TCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.KisiTemelBilgisi TemelBilgisi {
            get {
                return this.TemelBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.TemelBilgisiField, value) != true)) {
                    this.TemelBilgisiField = value;
                    this.RaisePropertyChanged("TemelBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre YakinlikKod {
            get {
                return this.YakinlikKodField;
            }
            set {
                if ((object.ReferenceEquals(this.YakinlikKodField, value) != true)) {
                    this.YakinlikKodField = value;
                    this.RaisePropertyChanged("YakinlikKod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NkoOlay", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class NkoOlay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DusunceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.KisiKayitYeriKodBilgisi KayitYeriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OlayAciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> OlayKayitNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi OlayTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre OlayTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dusunce {
            get {
                return this.DusunceField;
            }
            set {
                if ((object.ReferenceEquals(this.DusunceField, value) != true)) {
                    this.DusunceField = value;
                    this.RaisePropertyChanged("Dusunce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.KisiKayitYeriKodBilgisi KayitYeri {
            get {
                return this.KayitYeriField;
            }
            set {
                if ((object.ReferenceEquals(this.KayitYeriField, value) != true)) {
                    this.KayitYeriField = value;
                    this.RaisePropertyChanged("KayitYeri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OlayAciklama {
            get {
                return this.OlayAciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.OlayAciklamaField, value) != true)) {
                    this.OlayAciklamaField = value;
                    this.RaisePropertyChanged("OlayAciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> OlayKayitNo {
            get {
                return this.OlayKayitNoField;
            }
            set {
                if ((this.OlayKayitNoField.Equals(value) != true)) {
                    this.OlayKayitNoField = value;
                    this.RaisePropertyChanged("OlayKayitNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi OlayTarih {
            get {
                return this.OlayTarihField;
            }
            set {
                if ((object.ReferenceEquals(this.OlayTarihField, value) != true)) {
                    this.OlayTarihField = value;
                    this.RaisePropertyChanged("OlayTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre OlayTipi {
            get {
                return this.OlayTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.OlayTipiField, value) != true)) {
                    this.OlayTipiField = value;
                    this.RaisePropertyChanged("OlayTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiDurumBilgisi", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class KisiDurumBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre DinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre DurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre MedeniHalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi OlumTarihField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre Din {
            get {
                return this.DinField;
            }
            set {
                if ((object.ReferenceEquals(this.DinField, value) != true)) {
                    this.DinField = value;
                    this.RaisePropertyChanged("Din");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre Durum {
            get {
                return this.DurumField;
            }
            set {
                if ((object.ReferenceEquals(this.DurumField, value) != true)) {
                    this.DurumField = value;
                    this.RaisePropertyChanged("Durum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre MedeniHal {
            get {
                return this.MedeniHalField;
            }
            set {
                if ((object.ReferenceEquals(this.MedeniHalField, value) != true)) {
                    this.MedeniHalField = value;
                    this.RaisePropertyChanged("MedeniHal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi OlumTarih {
            get {
                return this.OlumTarihField;
            }
            set {
                if ((object.ReferenceEquals(this.OlumTarihField, value) != true)) {
                    this.OlumTarihField = value;
                    this.RaisePropertyChanged("OlumTarih");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiKayitYeriBilgisi", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class KisiKayitYeriBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AileSiraNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BireySiraNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre CiltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre IlceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AileSiraNo {
            get {
                return this.AileSiraNoField;
            }
            set {
                if ((this.AileSiraNoField.Equals(value) != true)) {
                    this.AileSiraNoField = value;
                    this.RaisePropertyChanged("AileSiraNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BireySiraNo {
            get {
                return this.BireySiraNoField;
            }
            set {
                if ((this.BireySiraNoField.Equals(value) != true)) {
                    this.BireySiraNoField = value;
                    this.RaisePropertyChanged("BireySiraNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre Cilt {
            get {
                return this.CiltField;
            }
            set {
                if ((object.ReferenceEquals(this.CiltField, value) != true)) {
                    this.CiltField = value;
                    this.RaisePropertyChanged("Cilt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre Il {
            get {
                return this.IlField;
            }
            set {
                if ((object.ReferenceEquals(this.IlField, value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OlayTarihBilgisi", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class OlayTarihBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi BosanmaTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi EvlenmeTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi TescilTarihField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi BosanmaTarih {
            get {
                return this.BosanmaTarihField;
            }
            set {
                if ((object.ReferenceEquals(this.BosanmaTarihField, value) != true)) {
                    this.BosanmaTarihField = value;
                    this.RaisePropertyChanged("BosanmaTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi EvlenmeTarih {
            get {
                return this.EvlenmeTarihField;
            }
            set {
                if ((object.ReferenceEquals(this.EvlenmeTarihField, value) != true)) {
                    this.EvlenmeTarihField = value;
                    this.RaisePropertyChanged("EvlenmeTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi TescilTarih {
            get {
                return this.TescilTarihField;
            }
            set {
                if ((object.ReferenceEquals(this.TescilTarihField, value) != true)) {
                    this.TescilTarihField = value;
                    this.RaisePropertyChanged("TescilTarih");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiTemelBilgisi", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class KisiTemelBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnneAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BabaAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.Parametre CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi DogumTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DogumYerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd {
            get {
                return this.AnneAdField;
            }
            set {
                if ((object.ReferenceEquals(this.AnneAdField, value) != true)) {
                    this.AnneAdField = value;
                    this.RaisePropertyChanged("AnneAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd {
            get {
                return this.BabaAdField;
            }
            set {
                if ((object.ReferenceEquals(this.BabaAdField, value) != true)) {
                    this.BabaAdField = value;
                    this.RaisePropertyChanged("BabaAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.Parametre Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceChecker4_8.NufusKayitOrnegi.TarihBilgisi DogumTarih {
            get {
                return this.DogumTarihField;
            }
            set {
                if ((object.ReferenceEquals(this.DogumTarihField, value) != true)) {
                    this.DogumTarihField = value;
                    this.RaisePropertyChanged("DogumTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYer {
            get {
                return this.DogumYerField;
            }
            set {
                if ((object.ReferenceEquals(this.DogumYerField, value) != true)) {
                    this.DogumYerField = value;
                    this.RaisePropertyChanged("DogumYer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TarihBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class TarihBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ay {
            get {
                return this.AyField;
            }
            set {
                if ((this.AyField.Equals(value) != true)) {
                    this.AyField = value;
                    this.RaisePropertyChanged("Ay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gun {
            get {
                return this.GunField;
            }
            set {
                if ((this.GunField.Equals(value) != true)) {
                    this.GunField = value;
                    this.RaisePropertyChanged("Gun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Yil {
            get {
                return this.YilField;
            }
            set {
                if ((this.YilField.Equals(value) != true)) {
                    this.YilField = value;
                    this.RaisePropertyChanged("Yil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiKayitYeriKodBilgisi", Namespace="http://kps.nvi.gov.tr/2021/04/01")]
    [System.SerializableAttribute()]
    public partial class KisiKayitYeriKodBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AileSiraNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BireySiraNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CiltKodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlceKodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AileSiraNo {
            get {
                return this.AileSiraNoField;
            }
            set {
                if ((this.AileSiraNoField.Equals(value) != true)) {
                    this.AileSiraNoField = value;
                    this.RaisePropertyChanged("AileSiraNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BireySiraNo {
            get {
                return this.BireySiraNoField;
            }
            set {
                if ((this.BireySiraNoField.Equals(value) != true)) {
                    this.BireySiraNoField = value;
                    this.RaisePropertyChanged("BireySiraNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CiltKod {
            get {
                return this.CiltKodField;
            }
            set {
                if ((this.CiltKodField.Equals(value) != true)) {
                    this.CiltKodField = value;
                    this.RaisePropertyChanged("CiltKod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlceKod {
            get {
                return this.IlceKodField;
            }
            set {
                if ((this.IlceKodField.Equals(value) != true)) {
                    this.IlceKodField = value;
                    this.RaisePropertyChanged("IlceKod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kps.nvi.gov.tr/2021/04/01", ConfigurationName="NufusKayitOrnegi.NkoSorgulaTCKimlikNoServis")]
    public interface NkoSorgulaTCKimlikNoServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kps.nvi.gov.tr/2021/04/01/NkoSorgulaTCKimlikNoServis/Sorgula", ReplyAction="http://kps.nvi.gov.tr/2021/04/01/NkoSorgulaTCKimlikNoServis/SorgulaResponse")]
        ServiceChecker4_8.NufusKayitOrnegi.NkoSonucu Sorgula(ServiceChecker4_8.NufusKayitOrnegi.NkoTCKimlikNoSorguKriteri[] kriterListesi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kps.nvi.gov.tr/2021/04/01/NkoSorgulaTCKimlikNoServis/Sorgula", ReplyAction="http://kps.nvi.gov.tr/2021/04/01/NkoSorgulaTCKimlikNoServis/SorgulaResponse")]
        System.Threading.Tasks.Task<ServiceChecker4_8.NufusKayitOrnegi.NkoSonucu> SorgulaAsync(ServiceChecker4_8.NufusKayitOrnegi.NkoTCKimlikNoSorguKriteri[] kriterListesi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NkoSorgulaTCKimlikNoServisChannel : ServiceChecker4_8.NufusKayitOrnegi.NkoSorgulaTCKimlikNoServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NkoSorgulaTCKimlikNoServisClient : System.ServiceModel.ClientBase<ServiceChecker4_8.NufusKayitOrnegi.NkoSorgulaTCKimlikNoServis>, ServiceChecker4_8.NufusKayitOrnegi.NkoSorgulaTCKimlikNoServis {
        
        public NkoSorgulaTCKimlikNoServisClient() {
        }
        
        public NkoSorgulaTCKimlikNoServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NkoSorgulaTCKimlikNoServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NkoSorgulaTCKimlikNoServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NkoSorgulaTCKimlikNoServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceChecker4_8.NufusKayitOrnegi.NkoSonucu Sorgula(ServiceChecker4_8.NufusKayitOrnegi.NkoTCKimlikNoSorguKriteri[] kriterListesi) {
            return base.Channel.Sorgula(kriterListesi);
        }
        
        public System.Threading.Tasks.Task<ServiceChecker4_8.NufusKayitOrnegi.NkoSonucu> SorgulaAsync(ServiceChecker4_8.NufusKayitOrnegi.NkoTCKimlikNoSorguKriteri[] kriterListesi) {
            return base.Channel.SorgulaAsync(kriterListesi);
        }
    }
}
