//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceChecker4_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class kontrol
    {
        public int id { get; set; }
        public string adsoyad { get; set; }
        public string tc { get; set; }
        public string dogumGun { get; set; }
        public string dogumAy { get; set; }
        public string dogumYil { get; set; }
        public string no { get; set; }
        public string mernis_acik_adres { get; set; }
    }
}
